service: nodeless

provider:
  name: aws
  runtime: nodejs10.x
  region: us-east-1
  stage: prod
  memorySize: 128
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:GetObject
        - s3:PutObject
      Resource:
        - "arn:aws:s3:::*"

functions:
  optimize:
    handler: optimize.handle
    environment:
      bucket: wi-nodeless
    events:
      - s3:
          bucket: wi-nodeless
          event: s3:ObjectCreated:*
          rules:
            - prefix: uploads/
            - suffix: .jpg
      - s3:
          bucket: wi-nodeless
          event: s3:ObjectCreated:*
          rules:
            - prefix: uploads/
            - suffix: .jpeg
      - s3:
          bucket: wi-nodeless
          event: s3:ObjectCreated:*
          rules:
            - prefix: uploads/
            - suffix: .png
